# This file was manually created.
# We have a script at /scripts/generate-dependabot.mjs to generate
# a entry for every package, but we're trying manual for now.

version: 2
updates:
  # Experiment with analyzing only the root package. We don't like having a PR
  # for every subpackage, and we expect that bumping this package will cause the
  # yarn.lock to bump the resolved versions for all the subpackages.
  - package-ecosystem: npm
    # TODO try the `directories` option to get all the subpackages
    directory: /.
    schedule:
      interval: weekly
    commit-message:
      prefix: chore
    groups:
      all-minor-patch:
        patterns:
          - '*'
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: chore
