catalogs:
  dev:
    typescript: ~6.0.3
    eslint: ^10.7.0

packageExtensions:
  # workaround for @jessie.js/eslint-plugin eagerly attempting to resolve
  # transitive deps for legacy eslint versions.
  '@jessie.js/eslint-plugin@*':
    dependencies:
      eslint-plugin-jsdoc: ^50.8.0
      eslint-config-prettier: ^10.1.8
      eslint-plugin-import: 'npm:eslint-plugin-import-x@4.16.2'

enableScripts: false

nodeLinker: pnpm
