catalogs:
  testing:
    ava: ^6.4.1
    c8: ^7.14.0
    tsd: ^0.32.0
    eslint: ^8.57.1
    eslint-config-airbnb-base: ^15.0.0
    eslint-config-prettier: ^9.1.0
    eslint-plugin-eslint-comments: ^3.2.0
    eslint-plugin-import: ^2.31.0

nodeLinker: node-modules
