export type * from './src/types.js';
export {
  makeGit,
  isGitReadOnly,
  getGitBackend,
  makeNotYetImplementedBackend,
  makeGitFsBackend,
  makeGitRemoteEndpoint,
  makeGitRemote,
  makeGitCloner,
  getGitRemoteController,
  makeBasicCredential,
  makeBearerCredential,
  makeUnavailableGitCredential,
  assertGitCredentialForUrl,
  revokeGitCredential,
  getGitCredentialController,
  GitInterface,
  GitTreeInterface,
  GitRemoteInterface,
  GitRemoteControllerInterface,
  GitCredentialControllerInterface,
  BasicCredentialInterface,
  BearerCredentialInterface,
} from './src/index.js';
