/*
 * Endo OS — seL4 Microkit Protection Domain (Phase 0b)
 *
 * Boots on the formally verified seL4 kernel, initializes QuickJS,
 * applies SES lockdown, and runs the Endo bootstrap.
 *
 * QuickJS runs entirely in our protection domain with a 16 MB heap
 * managed by our own allocator.  No libc, no POSIX — just the
 * verified kernel and our code.
 */

#include <microkit.h>
#include <stdint.h>
#include "quickjs.h"

/* Memory region mapped by the Microkit system description. */
uintptr_t js_heap_vaddr;

/* Embedded JS sources (generated by the build). */
extern const char js_ses_lockdown[];
extern const int js_ses_lockdown_len;
extern const char js_bootstrap[];
extern const int js_bootstrap_len;

/* print() — bridge QuickJS to seL4 debug console. */
static JSValue js_print(JSContext *ctx, JSValueConst this_val,
                        int argc, JSValueConst *argv) {
    for (int i = 0; i < argc; i++) {
        if (i > 0) microkit_dbg_puts(" ");
        const char *str = JS_ToCString(ctx, argv[i]);
        if (str) {
            microkit_dbg_puts(str);
            JS_FreeCString(ctx, str);
        }
    }
    microkit_dbg_puts("\n");
    return JS_UNDEFINED;
}

/* Run a JS source string and report errors. */
static int eval_source(JSContext *ctx, const char *source, int len,
                       const char *filename) {
    JSValue val = JS_Eval(ctx, source, len, filename,
                          JS_EVAL_TYPE_GLOBAL);
    if (JS_IsException(val)) {
        JSValue exc = JS_GetException(ctx);
        const char *msg = JS_ToCString(ctx, exc);
        if (msg) {
            microkit_dbg_puts("ERROR: ");
            microkit_dbg_puts(msg);
            microkit_dbg_puts("\n");
            JS_FreeCString(ctx, msg);
        }
        /* Print stack trace if available. */
        JSValue stack = JS_GetPropertyStr(ctx, exc, "stack");
        if (!JS_IsUndefined(stack)) {
            const char *stack_str = JS_ToCString(ctx, stack);
            if (stack_str) {
                microkit_dbg_puts(stack_str);
                microkit_dbg_puts("\n");
                JS_FreeCString(ctx, stack_str);
            }
        }
        JS_FreeValue(ctx, stack);
        JS_FreeValue(ctx, exc);
        JS_FreeValue(ctx, val);
        return -1;
    }
    JS_FreeValue(ctx, val);
    return 0;
}

void init(void) {
    microkit_dbg_puts("endo-init: Endo OS starting (seL4 + QuickJS)\n");
    microkit_dbg_puts("endo-init: Formally verified capability-native OS\n");

    /* Create QuickJS runtime with our heap. */
    microkit_dbg_puts("endo-init: Initializing QuickJS runtime\n");
    JSRuntime *rt = JS_NewRuntime();
    if (!rt) {
        microkit_dbg_puts("endo-init: FATAL: JS_NewRuntime failed\n");
        return;
    }

    /* Limit memory to our 16 MB heap. */
    JS_SetMemoryLimit(rt, 14 * 1024 * 1024);  /* Leave 2MB for allocator overhead */

    JSContext *ctx = JS_NewContext(rt);
    if (!ctx) {
        microkit_dbg_puts("endo-init: FATAL: JS_NewContext failed\n");
        JS_FreeRuntime(rt);
        return;
    }

    microkit_dbg_puts("endo-init: QuickJS runtime ready\n");

    /* Install print() global. */
    JSValue global = JS_GetGlobalObject(ctx);
    JS_SetPropertyStr(ctx, global, "print",
        JS_NewCFunction(ctx, js_print, "print", 1));
    JS_FreeValue(ctx, global);

    /* Run SES lockdown. */
    microkit_dbg_puts("endo-init: Loading SES lockdown\n");
    if (eval_source(ctx, js_ses_lockdown, js_ses_lockdown_len,
                    "ses-lockdown.js") != 0) {
        microkit_dbg_puts("endo-init: SES lockdown FAILED\n");
    } else {
        microkit_dbg_puts("endo-init: SES lockdown complete\n");
    }

    /* Run bootstrap. */
    microkit_dbg_puts("endo-init: Running bootstrap\n");
    if (eval_source(ctx, js_bootstrap, js_bootstrap_len,
                    "bootstrap.js") != 0) {
        microkit_dbg_puts("endo-init: Bootstrap FAILED\n");
    } else {
        microkit_dbg_puts("endo-init: Bootstrap complete\n");
    }

    /* In later phases, the context stays alive and the event loop
       processes notifications from device driver PDs.  For Phase 0b,
       we just verify JS works and return to the Microkit event loop. */

    /* Don't free — the context stays alive for the PD's lifetime.
       JS_FreeContext(ctx);
       JS_FreeRuntime(rt); */
}

void notified(microkit_channel channel) {
    /* Phase 1+: dispatch device I/O to JS callbacks. */
    (void)channel;
}
