// endo-init: PID 1 for Endo OS
//
// Embeds V8, applies SES lockdown, and evaluates the Endo daemon
// bootstrap script.  This is the only native process in the system.
// All further isolation is provided by V8 Isolates and SES
// Compartments.

#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <fcntl.h>
#include <unistd.h>
#include <sys/stat.h>

#include "v8.h"
#include "libplatform/libplatform.h"

#include "platform.h"

// Embedded JS sources — linked in at build time as binary blobs.
// The linker symbols are generated by the build from .js files.
extern "C" {
  extern const char _binary_ses_lockdown_js_start[];
  extern const char _binary_ses_lockdown_js_end[];
  extern const char _binary_bootstrap_js_start[];
  extern const char _binary_bootstrap_js_end[];
}

namespace endo {

// Read a file into a newly allocated buffer.  Returns nullptr on
// failure.  Caller owns the returned memory.
static char* ReadFile(const char* path, size_t* out_size) {
  int fd = open(path, O_RDONLY);
  if (fd < 0) return nullptr;

  struct stat st;
  if (fstat(fd, &st) != 0) {
    close(fd);
    return nullptr;
  }

  size_t size = static_cast<size_t>(st.st_size);
  char* buf = static_cast<char*>(malloc(size + 1));
  if (!buf) {
    close(fd);
    return nullptr;
  }

  size_t total = 0;
  while (total < size) {
    ssize_t n = read(fd, buf + total, size - total);
    if (n <= 0) {
      free(buf);
      close(fd);
      return nullptr;
    }
    total += static_cast<size_t>(n);
  }
  buf[size] = '\0';
  close(fd);

  if (out_size) *out_size = size;
  return buf;
}

// Compile and run a JS source string in the given context.
// Returns the result as a v8::Value, or an empty handle on error.
static v8::MaybeLocal<v8::Value> EvalSource(
    v8::Isolate* isolate,
    v8::Local<v8::Context> context,
    const char* source_str,
    size_t source_len,
    const char* origin_name) {

  v8::EscapableHandleScope handle_scope(isolate);
  v8::Context::Scope context_scope(context);

  v8::Local<v8::String> source =
      v8::String::NewFromUtf8(isolate, source_str,
                              v8::NewStringType::kNormal,
                              static_cast<int>(source_len))
          .ToLocalChecked();

  v8::Local<v8::String> origin_str =
      v8::String::NewFromUtf8(isolate, origin_name,
                              v8::NewStringType::kNormal)
          .ToLocalChecked();

  v8::ScriptOrigin origin(origin_str);

  v8::Local<v8::Script> script;
  if (!v8::Script::Compile(context, source, &origin).ToLocal(&script)) {
    return v8::MaybeLocal<v8::Value>();
  }

  v8::Local<v8::Value> result;
  if (!script->Run(context).ToLocal(&result)) {
    return v8::MaybeLocal<v8::Value>();
  }

  return handle_scope.Escape(result);
}

// The print() global — writes to stdout (serial console on bare metal).
static void PrintCallback(const v8::FunctionCallbackInfo<v8::Value>& info) {
  v8::Isolate* isolate = info.GetIsolate();
  v8::HandleScope handle_scope(isolate);

  for (int i = 0; i < info.Length(); i++) {
    if (i > 0) fputc(' ', stdout);
    v8::String::Utf8Value str(isolate, info[i]);
    if (*str) {
      fputs(*str, stdout);
    }
  }
  fputc('\n', stdout);
  fflush(stdout);
}

// Install minimal global bindings that the SES lockdown and Endo
// daemon need from the host.
static void InstallGlobals(v8::Isolate* isolate,
                           v8::Local<v8::ObjectTemplate> global) {
  // print(args...) — serial console output
  global->Set(
      v8::String::NewFromUtf8(isolate, "print",
                              v8::NewStringType::kNormal)
          .ToLocalChecked(),
      v8::FunctionTemplate::New(isolate, PrintCallback));

  // TODO(phase1): Add block device, crypto, network bindings
  // TODO(phase2): Add Isolate spawning for workers
}

// Report a V8 exception with stack trace to stderr.
static void ReportException(v8::Isolate* isolate,
                            v8::TryCatch* try_catch) {
  v8::HandleScope handle_scope(isolate);
  v8::String::Utf8Value exception(isolate, try_catch->Exception());
  const char* msg = *exception ? *exception : "<unknown error>";

  v8::Local<v8::Message> message = try_catch->Message();
  if (message.IsEmpty()) {
    fprintf(stderr, "endo-init: %s\n", msg);
    return;
  }

  v8::String::Utf8Value filename(isolate,
      message->GetScriptResourceName());
  int linenum = message->GetLineNumber(
      isolate->GetCurrentContext()).FromMaybe(-1);

  fprintf(stderr, "endo-init: %s:%d: %s\n",
          *filename ? *filename : "<unknown>",
          linenum, msg);

  v8::Local<v8::Value> stack_trace;
  if (try_catch->StackTrace(isolate->GetCurrentContext())
          .ToLocal(&stack_trace) &&
      stack_trace->IsString()) {
    v8::String::Utf8Value stack(isolate, stack_trace);
    if (*stack) fprintf(stderr, "%s\n", *stack);
  }
}

}  // namespace endo

int main(int argc, char* argv[]) {
  fprintf(stdout,
      "endo-init: Endo OS starting\n"
      "endo-init: Capability-native operating system\n");
  fflush(stdout);

  // Initialize V8.
  v8::V8::InitializeICUDefaultLocation(argv[0]);
  v8::V8::InitializeExternalStartupData(argv[0]);

  // Use our minimal platform implementation.
  std::unique_ptr<v8::Platform> platform = endo::CreateEndoPlatform();
  v8::V8::InitializePlatform(platform.get());
  v8::V8::Initialize();

  // Create the single primary isolate.
  v8::Isolate::CreateParams create_params;
  create_params.array_buffer_allocator =
      v8::ArrayBuffer::Allocator::NewDefaultAllocator();
  v8::Isolate* isolate = v8::Isolate::New(create_params);

  {
    v8::Isolate::Scope isolate_scope(isolate);
    v8::HandleScope handle_scope(isolate);

    // Create global template with our host bindings.
    v8::Local<v8::ObjectTemplate> global = v8::ObjectTemplate::New(isolate);
    endo::InstallGlobals(isolate, global);

    // Create the primary context.
    v8::Local<v8::Context> context =
        v8::Context::New(isolate, nullptr, global);
    v8::Context::Scope context_scope(context);

    v8::TryCatch try_catch(isolate);

    // Phase 0: Evaluate SES lockdown.
    // In the final build, these come from linked binary blobs.
    // For development, try loading from files first.
    const char* ses_source = nullptr;
    size_t ses_len = 0;
    char* ses_file = nullptr;

    ses_file = endo::ReadFile("/ses-lockdown.js", &ses_len);
    if (ses_file) {
      ses_source = ses_file;
      fprintf(stdout, "endo-init: Loaded SES from /ses-lockdown.js\n");
    } else {
      // Fall back to embedded blob.
      ses_source = _binary_ses_lockdown_js_start;
      ses_len = static_cast<size_t>(
          _binary_ses_lockdown_js_end - _binary_ses_lockdown_js_start);
      fprintf(stdout, "endo-init: Using embedded SES lockdown\n");
    }

    if (ses_source && ses_len > 0) {
      auto result = endo::EvalSource(
          isolate, context, ses_source, ses_len, "ses-lockdown.js");
      if (result.IsEmpty()) {
        fprintf(stderr, "endo-init: SES lockdown failed\n");
        endo::ReportException(isolate, &try_catch);
      } else {
        fprintf(stdout, "endo-init: SES lockdown complete\n");
      }
    }
    if (ses_file) free(ses_file);

    // Evaluate bootstrap script.
    const char* boot_source = nullptr;
    size_t boot_len = 0;
    char* boot_file = nullptr;

    boot_file = endo::ReadFile("/bootstrap.js", &boot_len);
    if (boot_file) {
      boot_source = boot_file;
      fprintf(stdout, "endo-init: Loaded bootstrap from /bootstrap.js\n");
    } else {
      boot_source = _binary_bootstrap_js_start;
      boot_len = static_cast<size_t>(
          _binary_bootstrap_js_end - _binary_bootstrap_js_start);
      fprintf(stdout, "endo-init: Using embedded bootstrap\n");
    }

    if (boot_source && boot_len > 0) {
      auto result = endo::EvalSource(
          isolate, context, boot_source, boot_len, "bootstrap.js");
      if (result.IsEmpty()) {
        fprintf(stderr, "endo-init: Bootstrap failed\n");
        endo::ReportException(isolate, &try_catch);
      } else {
        fprintf(stdout, "endo-init: Bootstrap complete\n");
      }
    }
    if (boot_file) free(boot_file);

    // Run the event loop until there is no more work.
    // In a full OS, this never returns — the daemon runs forever.
    endo::RunEventLoop(isolate, platform.get());
  }

  // Shutdown V8.
  isolate->Dispose();
  v8::V8::Dispose();
  v8::V8::DisposePlatform();
  delete create_params.array_buffer_allocator;

  fprintf(stdout, "endo-init: Shutdown complete\n");

  // As PID 1, if we exit, the kernel panics.  In production this
  // should never happen.  For Phase 0 testing, this is fine.
  return 0;
}
