// @ts-check
/* global process */

/**
 * Filesystem-backed persistence for the root genie's model
 * configuration.  Sub-task 96 of `TODO/92_genie_primordial.md`.
 *
 * Three operations:
 *   - {@link loadConfig} reads `<workspaceDir>/.genie/config.json`,
 *     validates the schema, and returns a {@link Config} or
 *     `undefined`.  Never throws — corrupt JSON, schema mismatch, and
 *     missing files all collapse to `undefined` (with a descriptive
 *     warning logged to the worker console).
 *   - {@link saveConfig} writes the config atomically: temp file,
 *     `fsync`, `rename`, `chmod 0600`.  POSIX `rename` is atomic on
 *     the same filesystem; on Windows the rename is best-effort and
 *     `chmod` is a no-op (logged as a warning).
 *   - {@link clearConfig} unlinks the file, treating ENOENT as a
 *     no-op so callers can `clearConfig` blindly.
 *
 * The on-disk schema is version 1 (only); future migrations bump the
 * version literal in `./types.js` and add a `migrate` step here.
 *
 * The boot-time stamping side-effect (copying credentials into
 * `process.env`) lives in `packages/genie/main.js` — keeping the
 * env-mutation layer separate from the file-I/O layer means tests
 * here do not need to defend against env leakage.
 */

import { promises as fs } from 'fs';
import { dirname, join } from 'path';

/** @import { Config, ConfigModel } from './types.js' */

/**
 * Relative path under the workspace where the persisted config lives.
 * Exported so callers (tests, the boot-time loader) can resolve the
 * absolute path without re-deriving the constant.
 */
export const CONFIG_REL_PATH = '.genie/config.json';
harden(CONFIG_REL_PATH);

/** Suffix used for the atomic-write temp file. */
const TMP_SUFFIX = '.tmp';

/** Current schema version.  Bump alongside `ConfigVersion` in `./types.js`. */
const CURRENT_VERSION = 1;

/**
 * README pointer written by {@link saveConfig}.  Operators reading
 * the file by hand see this pointer at the doc.
 */
export const README_TEXT = harden(
  'Generated by /model commit. Plaintext — see CLAUDE.md before checking in.',
);
harden(README_TEXT);

/**
 * Resolve the absolute path of the config file for a workspace.
 *
 * @param {string} workspaceDir
 * @returns {string}
 */
const resolveConfigPath = workspaceDir => join(workspaceDir, CONFIG_REL_PATH);

/**
 * Best-effort detection of POSIX-style filesystems.  Used to gate the
 * `chmod 0600` call so Windows runs do not fail loudly.
 *
 * @returns {boolean}
 */
const isPosixLike = () => process.platform !== 'win32';

/**
 * Validate that `value` is a plain `Record<string, string>`.
 *
 * @param {unknown} value
 * @returns {value is Record<string, string>}
 */
const isStringRecord = value => {
  if (!value || typeof value !== 'object') return false;
  if (Array.isArray(value)) return false;
  for (const v of Object.values(/** @type {Record<string, unknown>} */ (value))) {
    if (typeof v !== 'string') return false;
  }
  return true;
};

/**
 * Internal: schema-check a freshly-parsed JSON value.  Returns a
 * normalised {@link Config} on success, or `undefined` after logging
 * a descriptive warning.
 *
 * Normalisation steps:
 *   - `credentials` and `options` collapse to `{}` when absent;
 *   - the README is round-tripped only when the input value is a
 *     string;
 *   - extra top-level keys are dropped silently (forward-compat
 *     against future migrations that may stash auxiliary fields).
 *
 * @param {unknown} raw
 * @param {string} sourcePath - File path used in warning messages.
 * @returns {Config | undefined}
 */
export const validateConfig = (raw, sourcePath) => {
  if (!raw || typeof raw !== 'object') {
    console.warn(
      `[genie] persistence: ${sourcePath}: top-level value is not an object`,
    );
    return undefined;
  }
  const obj = /** @type {Record<string, unknown>} */ (raw);

  if (obj.version !== CURRENT_VERSION) {
    console.warn(
      `[genie] persistence: ${sourcePath}: unsupported schema version ${JSON.stringify(obj.version)} (expected ${CURRENT_VERSION})`,
    );
    return undefined;
  }

  const modelRaw = obj.model;
  if (!modelRaw || typeof modelRaw !== 'object') {
    console.warn(
      `[genie] persistence: ${sourcePath}: missing or invalid \`model\` field`,
    );
    return undefined;
  }
  const model = /** @type {Record<string, unknown>} */ (modelRaw);
  const { provider, modelId } = model;
  if (typeof provider !== 'string' || provider.length === 0) {
    console.warn(
      `[genie] persistence: ${sourcePath}: \`model.provider\` must be a non-empty string`,
    );
    return undefined;
  }
  if (typeof modelId !== 'string' || modelId.length === 0) {
    console.warn(
      `[genie] persistence: ${sourcePath}: \`model.modelId\` must be a non-empty string`,
    );
    return undefined;
  }

  const credsRaw = model.credentials === undefined ? {} : model.credentials;
  if (!isStringRecord(credsRaw)) {
    console.warn(
      `[genie] persistence: ${sourcePath}: \`model.credentials\` must be a Record<string,string>`,
    );
    return undefined;
  }
  const optsRaw = model.options === undefined ? {} : model.options;
  if (!isStringRecord(optsRaw)) {
    console.warn(
      `[genie] persistence: ${sourcePath}: \`model.options\` must be a Record<string,string>`,
    );
    return undefined;
  }

  /** @type {ConfigModel} */
  const normalisedModel = {
    provider,
    modelId,
    credentials: { ...credsRaw },
    options: { ...optsRaw },
  };

  /** @type {Config} */
  const config = {
    version: CURRENT_VERSION,
    model: normalisedModel,
  };
  // eslint-disable-next-line no-underscore-dangle
  const readme = obj._README;
  if (typeof readme === 'string') {
    // eslint-disable-next-line no-underscore-dangle
    config._README = readme;
  }
  return config;
};
harden(validateConfig);

/**
 * Read and validate `<workspaceDir>/.genie/config.json`.
 *
 * Sentinel handling — never throws:
 *   - file absent → `undefined`
 *   - JSON parse error → log a warning, return `undefined`
 *   - schema mismatch → {@link validateConfig} logs and returns
 *     `undefined`
 *
 * @param {string} workspaceDir
 * @returns {Promise<Config | undefined>}
 */
export const loadConfig = async workspaceDir => {
  await null;
  if (typeof workspaceDir !== 'string' || workspaceDir.length === 0) {
    throw new Error('loadConfig: workspaceDir must be a non-empty string');
  }
  const filePath = resolveConfigPath(workspaceDir);
  /** @type {string} */
  let text;
  try {
    text = await fs.readFile(filePath, 'utf8');
  } catch (err) {
    const code = /** @type {NodeJS.ErrnoException} */ (err).code;
    if (code === 'ENOENT') return undefined;
    console.warn(
      `[genie] persistence: failed to read ${filePath}: ${/** @type {Error} */ (err).message || String(err)}`,
    );
    return undefined;
  }
  /** @type {unknown} */
  let parsed;
  try {
    parsed = JSON.parse(text);
  } catch (err) {
    console.warn(
      `[genie] persistence: ${filePath}: invalid JSON (${/** @type {Error} */ (err).message || String(err)})`,
    );
    return undefined;
  }
  return validateConfig(parsed, filePath);
};
harden(loadConfig);

/**
 * Atomically write the config to
 * `<workspaceDir>/.genie/config.json`.  The temp file is created in
 * the same directory so the rename stays on a single filesystem
 * (POSIX `rename(2)` is atomic only when source and destination share
 * a filesystem).
 *
 * Steps:
 *   1. Normalise the config object: ensure `_README`, default empty
 *      `credentials` / `options` records, validate the schema.
 *   2. `mkdir -p <dir>` so the first call after `genie init` succeeds
 *      even when `.genie/` does not yet exist.
 *   3. Write to `<file>.tmp`, `fsync` the descriptor, `close`.
 *   4. `rename(<file>.tmp, <file>)`.
 *   5. `chmod 0600` on POSIX; log a warning on platforms where chmod
 *      is unsupported instead of throwing.
 *
 * @param {string} workspaceDir
 * @param {Config} config
 * @returns {Promise<void>}
 */
export const saveConfig = async (workspaceDir, config) => {
  await null;
  if (typeof workspaceDir !== 'string' || workspaceDir.length === 0) {
    throw new Error('saveConfig: workspaceDir must be a non-empty string');
  }
  if (!config || typeof config !== 'object') {
    throw new Error('saveConfig: config must be an object');
  }
  if (config.version !== CURRENT_VERSION) {
    throw new Error(
      `saveConfig: refusing to write schema version ${JSON.stringify(config.version)} (expected ${CURRENT_VERSION})`,
    );
  }
  const validated = validateConfig(config, '<saveConfig input>');
  if (!validated) {
    throw new Error('saveConfig: config failed schema validation');
  }

  // Force the canonical README pointer; operators editing the file by
  // hand see a pointer back to CLAUDE.md regardless of how the in-memory
  // draft was assembled.
  /** @type {Config & { _README: string }} */
  const toWrite = {
    // eslint-disable-next-line no-underscore-dangle
    _README: README_TEXT,
    version: validated.version,
    model: validated.model,
  };

  const filePath = resolveConfigPath(workspaceDir);
  const tmpPath = `${filePath}${TMP_SUFFIX}`;
  const dir = dirname(filePath);

  await fs.mkdir(dir, { recursive: true });

  // Open the temp file with mode 0600 directly so an interrupted
  // write never exposes a world-readable file (the rename below
  // preserves the temp's mode on POSIX).
  const fh = await fs.open(tmpPath, 'w', 0o600);
  try {
    const json = `${JSON.stringify(toWrite, null, 2)}\n`;
    await fh.writeFile(json, 'utf8');
    await fh.sync();
  } finally {
    await fh.close();
  }

  await fs.rename(tmpPath, filePath);

  if (isPosixLike()) {
    try {
      await fs.chmod(filePath, 0o600);
    } catch (err) {
      console.warn(
        `[genie] persistence: chmod 0600 ${filePath} failed: ${/** @type {Error} */ (err).message || String(err)}`,
      );
    }
  } else {
    console.warn(
      `[genie] persistence: chmod 0600 not supported on ${process.platform}; ${filePath} retains its default ACL`,
    );
  }
};
harden(saveConfig);

/**
 * Remove `<workspaceDir>/.genie/config.json`, ignoring "file not
 * found" errors so callers can clear blindly.  Other I/O errors
 * surface as a thrown `Error` because they indicate something the
 * operator should investigate (permission denied, etc.).
 *
 * @param {string} workspaceDir
 * @returns {Promise<void>}
 */
export const clearConfig = async workspaceDir => {
  await null;
  if (typeof workspaceDir !== 'string' || workspaceDir.length === 0) {
    throw new Error('clearConfig: workspaceDir must be a non-empty string');
  }
  const filePath = resolveConfigPath(workspaceDir);
  try {
    await fs.unlink(filePath);
  } catch (err) {
    const code = /** @type {NodeJS.ErrnoException} */ (err).code;
    if (code === 'ENOENT') return;
    throw err;
  }
};
harden(clearConfig);
