#!/bin/bash

OS="$(uname -s)"

case "$OS" in
    Linux*)
        OS_DIR="linux64-bin"
        ;;
    Darwin*)
        OS_DIR="osx-bin"
        ;;
    CYGWIN*|MINGW*|MSYS*)
        OS_DIR="win64-bin"
        ;;
    *)
        echo "Unsupported OS: $OS"
        exit 1
        ;;
esac

# Paths relative to 'packages/ses'
HERMESC="../../../hermes-cli-darwin-v0.12.0/hermesc" # HBC v89
HERMES="../../../hermes-cli-darwin-v0.12.0/hermes"  # HBC v89

# HERMESC="../../../hermes-cli-darwin/hermesc" # v0.13.0, HBC v96
# HERMES="../../../hermes-cli-darwin/hermes" # v0.13.0, HBC v96

echo "Concatenating: dist/ses-hermes.cjs + test/hermes-smoke.js"
cat dist/ses-hermes.cjs test/hermes-smoke.js > test/hermes-smoke-dist.js
echo "Generated: test/hermes-smoke-dist.js"

# Errors on async arrow functions and async generators
# Both are unsupported on Hermes
echo "Executing: test/hermes-smoke-dist.js on Hermes compiler"
$HERMESC test/hermes-smoke-dist.js -emit-binary -out test/hermes-smoke-dist.hbc
echo "Generated: test/hermes-smoke-dist.hbc"
echo "Hermes compiler done"

# TODO: Disabled until https://github.com/endojs/endo/issues/1891 complete
echo "Executing generated bytecode file on Hermes VM"
$HERMES -b test/hermes-smoke-dist.hbc
echo "Hermes VM done"

echo "Hermes tests complete"

echo "Removing: test/hermes-smoke-dist.js"
rm test/hermes-smoke-dist.js
echo "Removing: test/hermes-smoke-dist.hbc"
rm test/hermes-smoke-dist.hbc
