#!/bin/bash

# Creates a JS smoke test to be compiled into Hermes bytecode (hbc).
#
# Usage: scripts/hermes-test.sh

set -ueo pipefail

DIR=$(dirname -- "${BASH_SOURCE[0]}")
cd "$DIR/.."

OS="$(uname -s)"

case "$OS" in
    Linux*)
        OS_DIR="linux64-bin"
        ;;
    Darwin*)
        OS_DIR="osx-bin"
        ;;
    CYGWIN*|MINGW*|MSYS*)
        OS_DIR="win64-bin"
        ;;
    *)
        echo "Unsupported OS: $OS"
        exit 1
        ;;
esac

HERMESC="../../node_modules/hermes-engine-cli/$OS_DIR/hermesc"
HERMES="../../node_modules/hermes-engine-cli/$OS_DIR/hermes"

echo "Concatenating: dist/ses-hermes.cjs + test/_hermes-smoke.js"
cat dist/ses-hermes.cjs test/_hermes-smoke.js > test/_hermes-smoke-dist.js
echo "Generated: test/_hermes-smoke-dist.js"

# Errors on async arrow functions and async generators
# Both are unsupported on Hermes
echo "Executing: test/_hermes-smoke-dist.js on Hermes compiler"
$HERMESC test/_hermes-smoke-dist.js -emit-binary -out test/_hermes-smoke-dist.hbc
echo "Generated: test/_hermes-smoke-dist.hbc"
echo "Hermes compiler done"

# TODO: Disabled until https://github.com/endojs/endo/issues/1891 complete
# echo "Executing generated bytecode file on Hermes VM"
# $HERMES -b test/_hermes-smoke-dist.hbc
# echo "Hermes VM done"
echo "Skipping: Hermes VM"

echo "Hermes tests complete"

echo "Removing: test/_hermes-smoke-dist.js"
rm test/_hermes-smoke-dist.js
echo "Removing: test/_hermes-smoke-dist.hbc"
rm test/_hermes-smoke-dist.hbc
